# Generated by Django 3.2.12 on 2022-10-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campos',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
    ]
