# Generated by Django 3.2.12 on 2022-10-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0004_alter_campos_preco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campos',
            old_name='preco',
            new_name='preco_hr',
        ),
    ]
