# Generated by Django 3.2.12 on 2022-11-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0005_rename_preco_campos_preco_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField()),
            ],
        ),
    ]
